[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fed_program = "HBsfAtXFmgsr5EHDqiDJDyjuGVHhYU7ACWaEhKpVACqz"

[programs.devnet]
fed_program = "HBsfAtXFmgsr5EHDqiDJDyjuGVHhYU7ACWaEhKpVACqz"

[programs.mainnet]
fed_program = "HBsfAtXFmgsr5EHDqiDJDyjuGVHhYU7ACWaEhKpVACqz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/ubuntu/fed/script/keypair_distro.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
